In [1]:
!pip install --upgrade pip setuptools wheel
!pip install --upgrade pyarrow==17.0.0
!pip install "awswrangler[redshift]" --no-build-isolation
!pip install psycopg2-binary

Requirement already satisfied: pip in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (26.0.1)
Requirement already satisfied: setuptools in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (82.0.1)
Requirement already satisfied: wheel in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (0.46.3)
Requirement already satisfied: packaging>=24.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from wheel) (24.2)
Requirement already satisfied: pyarrow==17.0.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (17.0.0)
Requirement already satisfied: numpy>=1.16.6 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from pyarrow==17.0.0) (1.26.4)
Requirement already satisfied: awswrangler[redshift] in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (3.15.1)
Requirement already satisfied: boto3<2,>=1.20.32 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from awswrangler[redshift]) (1.42.69)
Requirement already satisfied: botocore<2,>=1.23.32 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from awswrangler[redshift]) (1.42.69)
Requirement already satisfied: numpy<3.0,>=1.26 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from awswrangler[redshift]) (1.26.4)
Requirement already satisfied: packaging<27.0,>=21.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from awswrangler[redshift]) (24.2)
Requirement already satisfied: pandas<3.0.0,>=1.2.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from awswrangler[redshift]) (2.3.3)
Requirement already satisfied: pyarrow<23.0.0,>=8.0.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from awswrangler[redshift]) (17.0.0)
Requirement already satisfied: setuptools in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from awswrangler[redshift]) (82.0.1)
Requirement already satisfied: typing-extensions<5,>=4.4.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from awswrangler[redshift]) (4.15.0)
Requirement already satisfied: redshift-connector<3,>=2.0.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from awswrangler[redshift]) (2.1.13)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from boto3<2,>=1.20.32->awswrangler[redshift]) (1.1.0)
Requirement already satisfied: s3transfer<0.17.0,>=0.16.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from boto3<2,>=1.20.32->awswrangler[redshift]) (0.16.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from botocore<2,>=1.23.32->awswrangler[redshift]) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from botocore<2,>=1.23.32->awswrangler[redshift]) (2.6.3)
Requirement already satisfied: pytz>=2020.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from pandas<3.0.0,>=1.2.0->awswrangler[redshift]) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from pandas<3.0.0,>=1.2.0->awswrangler[redshift]) (2025.3)
Requirement already satisfied: six>=1.5 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<2,>=1.23.32->awswrangler[redshift]) (1.17.0)
Requirement already satisfied: scramp<1.5.0,>=1.2.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from redshift-connector<3,>=2.0.0->awswrangler[redshift]) (1.4.8)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.13.5 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from redshift-connector<3,>=2.0.0->awswrangler[redshift]) (4.14.3)
Requirement already satisfied: requests<3.0.0,>=2.23.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from redshift-connector<3,>=2.0.0->awswrangler[redshift]) (2.32.5)
Requirement already satisfied: lxml<=6.0.2,>=4.6.5 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from redshift-connector<3,>=2.0.0->awswrangler[redshift]) (6.0.2)
Requirement already satisfied: soupsieve>=1.6.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from beautifulsoup4<5.0.0,>=4.13.5->redshift-connector<3,>=2.0.0->awswrangler[redshift]) (2.8.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from requests<3.0.0,>=2.23.0->redshift-connector<3,>=2.0.0->awswrangler[redshift]) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from requests<3.0.0,>=2.23.0->redshift-connector<3,>=2.0.0->awswrangler[redshift]) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from requests<3.0.0,>=2.23.0->redshift-connector<3,>=2.0.0->awswrangler[redshift]) (2026.1.4)
Requirement already satisfied: asn1crypto>=1.5.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (from scramp<1.5.0,>=1.2.0->redshift-connector<3,>=2.0.0->awswrangler[redshift]) (1.5.1)
Requirement already satisfied: psycopg2-binary in /home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages (2.9.11)

In [2]:
import os
import IPython
from IPython.display import display, Javascript
import pandas as pd
import redshift_connector
import awswrangler as wr
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta
import os
import boto3
import io
import pytz

# 1. Calcular fecha de mañana

In [3]:
fecha_tomorrow = (
    datetime.now(pytz.timezone("America/Lima")) + timedelta(days=1)
).strftime("%Y-%m-%d")
#fecha_tomorrow = "2024-10-28"
fecha_tomorrow

'2026-04-01'

# 2. Leemos PS de diferentes paises

## 2.1 Panama

In [4]:
try:
    # ps_pan = pd.read_csv(f"PS_Panama/Output/PS_todo_panama/D_base_pedidos_{fecha_tomorrow}.csv")
    ps_pan = pd.read_csv(f"s3://aje-analytics-ps-backup/PS_Panama/Output/PS_todo_panama/D_base_pedidos_{fecha_tomorrow}.csv")
except FileNotFoundError:
    ps_pan = pd.DataFrame()
    print("File not found")

/home/ec2-user/anaconda3/envs/python3/lib/python3.12/site-packages/fsspec/registry.py:301: UserWarning: Your installed version of s3fs is very old and known to cause
severe performance issues, see also https://github.com/dask/dask/issues/10276

To fix, you should specify a lower version bound on s3fs, or
update the current installation.

  warnings.warn(s3_msg)

In [5]:
ps_pan.shape

(4145, 9)

## 2.2 Peru

In [6]:
try:
    # ps_peru = pd.read_csv(f"PS_Peru/Output/PS_piloto_v1/D_base_pedidos_{fecha_tomorrow}.csv")
    ps_peru = pd.read_csv(f"s3://aje-analytics-ps-backup/PS_Peru/Output/PS_piloto_v1/D_base_pedidos_{fecha_tomorrow}.csv")
except FileNotFoundError:
    ps_peru = pd.DataFrame()
    print("File not found")

In [7]:
ps_peru.shape

(81017, 9)

## 2.3 Ecuador

In [8]:
try:
    # ps_ecuador = pd.read_csv(f"PS_Ecuador/Output/PS_piloto_v1/D_base_pedidos_{fecha_tomorrow}.csv")
    ps_ecuador = pd.read_csv(f"s3://aje-analytics-ps-backup/PS_Ecuador/Output/PS_piloto_v1/D_base_pedidos_{fecha_tomorrow}.csv")
except FileNotFoundError:
    ps_ecuador = pd.DataFrame()
    print("File not found")

In [9]:
ps_ecuador.shape

(43587, 9)

## 2.4 Costa Rica

In [10]:
try:
    # ps_costarica = pd.read_csv(f"PS_CostaRica/Output/PS_piloto_v1/D_base_pedidos_{fecha_tomorrow}.csv")
    ps_costarica = pd.read_csv(f"s3://aje-analytics-ps-backup/PS_CostaRica/Output/PS_piloto_v1/D_base_pedidos_{fecha_tomorrow}.csv")
except FileNotFoundError:
    ps_costarica = pd.DataFrame()
    print("File not found")

In [11]:
ps_costarica.shape

(4301, 9)

In [12]:
ps_costarica

,Pais,Compania,Sucursal,Cliente,Modulo,Producto,Cajas,Unidades,Fecha
0,CR,70,2,10859,1109,500862,1,0,2026-04-01
1,CR,70,2,11254,1109,599266,1,0,2026-04-01
2,CR,70,2,11254,1109,523155,1,0,2026-04-01
3,CR,70,2,11257,1120,599266,1,0,2026-04-01
4,CR,70,2,11689,1130,523144,1,0,2026-04-01
...,...,...,...,...,...,...,...,...,...
4296,CR,70,2,96719,1145,599266,1,0,2026-04-01
4297,CR,70,4,96721,16009,517507,1,0,2026-04-01
4298,CR,70,4,96721,16009,508471,1,0,2026-04-01
4299,CR,70,9,96726,6125,508471,1,0,2026-04-01
4300,CR,70,2,96785,12533,523135,1,0,2026-04-01

In [13]:
try:
    # ps_costarica = pd.read_csv(f"PS_CostaRica/Output/PS_piloto_v1/D_base_pedidos_{fecha_tomorrow}.csv")
    ps_costarica2 = pd.read_csv(f"s3://aje-analytics-ps-backup/PS_CostaRica/Output/PS_piloto_v1/D_base_pedidos_{fecha_tomorrow}_test.csv")
except FileNotFoundError:
    ps_costarica2 = pd.DataFrame()
    print("File not found")

In [14]:
ps_costarica2.shape

(4381, 9)

In [15]:
ps_costarica2

,Pais,Compania,Sucursal,Cliente,Modulo,Producto,Cajas,Unidades,Fecha
0,CR,70,2,10859,1109,501109,1,0,2026-04-01
1,CR,70,2,11254,1109,599266,1,0,2026-04-01
2,CR,70,2,11254,1109,523155,1,0,2026-04-01
3,CR,70,2,11257,1120,599266,1,0,2026-04-01
4,CR,70,2,11689,1130,523144,1,0,2026-04-01
...,...,...,...,...,...,...,...,...,...
4376,CR,70,4,96721,16009,517507,1,0,2026-04-01
4377,CR,70,4,96721,16009,508471,1,0,2026-04-01
4378,CR,70,6,96723,7123,524463,1,0,2026-04-01
4379,CR,70,9,96726,6125,508471,1,0,2026-04-01
4380,CR,70,2,96785,12533,523133,1,0,2026-04-01

## 2.5 FFVV Peru

In [16]:
try:
    # ps_peruNuevasCat = pd.read_csv(f"PS_Peru_NuevasCategorias/Output/PS_piloto_v1/D_base_pedidos_{fecha_tomorrow}.csv")
    ps_peruNuevasCat = pd.read_csv(f"s3://aje-analytics-ps-backup/PS_Peru_NuevasCategorias/Output/PS_piloto_v1/D_base_pedidos_{fecha_tomorrow}.csv")
except FileNotFoundError:
    ps_peruNuevasCat = pd.DataFrame()
    print("File not found")

File not found

In [17]:
ps_peruNuevasCat.shape

(0, 0)

## 2.6 Mexico

In [18]:
try:
    # ps_mexico = pd.read_csv(f"PS_Mexico/Output/PS_piloto_v1/D_base_pedidos_{fecha_tomorrow}.csv")
    ps_mexico = pd.read_csv(f"s3://aje-analytics-ps-backup/PS_Mexico/Output/PS_piloto_v1/D_base_pedidos_{fecha_tomorrow}.csv")
except FileNotFoundError:
    ps_mexico = pd.DataFrame()
    print("File not found")

In [19]:
ps_mexico.shape

(345, 9)

## 2.7 Guatemala

In [20]:
try:
    ps_guatemala = pd.read_csv(f"s3://aje-analytics-ps-backup/PS_Guatemala/Output/PS_piloto_v1/D_base_pedidos_{fecha_tomorrow}.csv")
except FileNotFoundError:
    ps_guatemala = pd.DataFrame()
    print("File not found")

In [21]:
ps_guatemala.shape

(28544, 9)

## 2.8 Nicaragua

In [22]:
try:
    ps_nicaragua = pd.read_csv(f"s3://aje-analytics-ps-backup/PS_Nicaragua/Output/PS_piloto_v1/D_base_pedidos_{fecha_tomorrow}.csv")
except FileNotFoundError:
    ps_nicaragua = pd.DataFrame()
    print("File not found")

In [23]:
ps_nicaragua.shape

(10130, 9)

# 3. Combinamos PS de los paises

In [24]:
# Nombrar paises
paises_a_concatenar = [ps_pan, ps_ecuador, ps_costarica, ps_mexico, ps_guatemala, ps_nicaragua, ps_peru]

In [25]:
final_ps = pd.concat(paises_a_concatenar, ignore_index=True)

In [26]:
final_ps.dtypes

Pais        object
Compania     int64
Sucursal     int64
Cliente      int64
Modulo       int64
Producto     int64
Cajas        int64
Unidades     int64
Fecha       object
dtype: object

In [27]:
final_ps["Compania"] = final_ps["Compania"].apply(lambda x: str(int(x)).rjust(4, "0"))
final_ps["Sucursal"] = final_ps["Sucursal"].apply(lambda x: str(int(x)).rjust(2, "0"))

In [28]:
final_ps['tipoRecomendacion'] = final_ps.groupby(['Pais', 'Compania', 'Sucursal', 'Cliente'])\
               .cumcount()\
               .apply(lambda x: f'PS{x+1}')

In [29]:
final_ps["ultFecha"] = ''
final_ps["Destacar"] = 'true'

---

## Concatenar con Pedido Estrategico y Recurrente (ECUADOR) -> (NO CRUZA, CONCATENA)

---

In [30]:
# Leemos PEDIDO ESTRATEGICO
s3 = boto3.client('s3')
bucket_name = "aje-analytics-ps-backup"
file_key = f"Pedido_Estrategico/Ecuador/Output/estr_base_pedidos_{fecha_tomorrow}.csv"

# 2. Descargar el objeto del S3 a la memoria RAM
response = s3.get_object(Bucket=bucket_name, Key=file_key)

# 3. Leerlo con Pandas sin pasar por s3fs
p_est = pd.read_csv(io.BytesIO(response['Body'].read()), 
    dtype={'Compania': str, 'Sucursal': str , 'Producto': str})

p_est["ultFecha"] = ''
p_est["Destacar"] = 'true'

In [31]:
p_est

,Pais,Compania,Sucursal,Cliente,Modulo,Producto,Cajas,Unidades,Fecha,tipoRecomendacion,ultFecha,Destacar
0,EC,0090,07,441206,377,508462,1,0,2026-04-01,PE1,,true
1,EC,0090,07,441206,377,524187,1,0,2026-04-01,PE2,,true
2,EC,0090,07,441206,377,524188,1,0,2026-04-01,PE3,,true
3,EC,0090,07,481994,90702,508462,1,0,2026-04-01,PE1,,true
4,EC,0090,07,481994,90702,524187,1,0,2026-04-01,PE2,,true
...,...,...,...,...,...,...,...,...,...,...,...,...
5826,EC,0090,03,438108,90,524187,1,0,2026-04-01,PE2,,true
5827,EC,0090,03,438108,90,524188,1,0,2026-04-01,PE3,,true
5828,EC,0090,07,419863,353,508462,1,0,2026-04-01,PE1,,true
5829,EC,0090,07,419863,353,524187,1,0,2026-04-01,PE2,,true
5830,EC,0090,07,419863,353,524188,1,0,2026-04-01,PE3,,true

In [32]:
# Leemos PEDIDO RECURRENTE
s3 = boto3.client('s3')
bucket_name = "aje-analytics-ps-backup"
file_key = f"Pedido_Recurrente/Ecuador/Output/recu_base_pedidos_{fecha_tomorrow}.csv"

# 2. Descargar el objeto del S3 a la memoria RAM
response = s3.get_object(Bucket=bucket_name, Key=file_key)

# 3. Leerlo con Pandas sin pasar por s3fs
p_rec = pd.read_csv(io.BytesIO(response['Body'].read()), 
    dtype={'Compania': str, 'Sucursal': str , 'Producto': str})

p_rec["Destacar"] = 'true'

In [33]:
p_rec

,Pais,Compania,Sucursal,Cliente,Modulo,Producto,Cajas,Unidades,Fecha,tipoRecomendacion,ultFecha,Destacar
0,EC,0090,07,105273,343,515517,1,0,2026-04-01,PR1,2026-03-19,true
1,EC,0090,07,105273,343,599653,1,0,2026-04-01,PR2,2026-03-19,true
2,EC,0090,07,105503,345,515904,1,0,2026-04-01,PR1,2026-03-26,true
3,EC,0090,07,105503,345,515517,1,0,2026-04-01,PR2,2026-03-26,true
4,EC,0090,07,105503,345,515519,1,0,2026-04-01,PR3,2026-03-16,true
...,...,...,...,...,...,...,...,...,...,...,...,...
10110,EC,0090,03,9025,70,515517,1,0,2026-04-01,PR1,2026-03-16,true
10111,EC,0090,03,9025,70,500010,1,0,2026-04-01,PR2,2026-03-05,true
10112,EC,0090,03,9025,70,515408,1,0,2026-04-01,PR3,2026-03-16,true
10113,EC,0090,03,9025,70,515904,1,0,2026-04-01,PR4,2026-03-19,true
10114,EC,0090,03,9025,70,517260,1,0,2026-04-01,PR5,2026-03-26,true

In [34]:
final_ps = pd.concat([p_est, p_rec, final_ps], ignore_index=True)

---

---

---

In [35]:
final_ps

,Pais,Compania,Sucursal,Cliente,Modulo,Producto,Cajas,Unidades,Fecha,tipoRecomendacion,ultFecha,Destacar
0,EC,0090,07,441206,377,508462,1,0,2026-04-01,PE1,,true
1,EC,0090,07,441206,377,524187,1,0,2026-04-01,PE2,,true
2,EC,0090,07,441206,377,524188,1,0,2026-04-01,PE3,,true
3,EC,0090,07,481994,90702,508462,1,0,2026-04-01,PE1,,true
4,EC,0090,07,481994,90702,524187,1,0,2026-04-01,PE2,,true
...,...,...,...,...,...,...,...,...,...,...,...,...
188010,PE,1003,03,9996,16946,622377,1,0,2026-04-01,PS3,,true
188011,PE,1003,03,9998,16970,608597,1,0,2026-04-01,PS1,,true
188012,PE,1003,03,9998,16970,622211,1,0,2026-04-01,PS2,,true
188013,PE,1003,03,9999,16922,608597,1,0,2026-04-01,PS1,,true
188014,PE,1003,03,9999,16922,699311,1,0,2026-04-01,PS2,,true

In [36]:
final_ps.shape

(188015, 12)

In [37]:
final_ps.tipoRecomendacion.value_counts().sort_index()

tipoRecomendacion
PE1      1945
PE2      1945
PE3      1941
PR1      1780
PR10      318
PR2      1728
PR3      1676
PR4      1606
PR5      1284
PR6       734
PR7       335
PR8       330
PR9       324
PS1     85497
PS2     55666
PS3     23978
PS4      6928
Name: count, dtype: int64

In [38]:
final_ps.groupby(["Pais","Compania"])["Cliente"].nunique()

Pais  Compania
CR    0070         2133
EC    0090        18870
GT    0076        12246
MX    0030          281
NI    0081         4209
PA    0096         2043
PE    0015          961
      0016         1872
      0018         1562
      0020        16295
      1003        24555
Name: Cliente, dtype: int64

In [39]:
# Total de clientes por Pais
final_ps.groupby(["Pais","Compania","Sucursal"]).Cliente.nunique().groupby("Pais").sum()

Pais
CR     2344
EC    18870
GT    12247
MX      281
NI     4209
PA     2043
PE    45562
Name: Cliente, dtype: int64

In [40]:
# Guardamos el PS final
final_ps.to_csv(
    f"Output/0_Final_PS/base_pedidos_final_{fecha_tomorrow}.csv", index=False
)

In [41]:
# Establecer la conexión con S3
bucket_name = 'aje-analytics-ps-backup'  # nombre de bucket en S3
file_name = f'Output/0_Final_PS/base_pedidos_final_{fecha_tomorrow}.csv'  # nombre para el archivo en S3
s3_path = f's3://{bucket_name}/{file_name}'

# Escribir el dataframe en S3 con AWS Data Wrangler
wr.s3.to_csv(final_ps, s3_path, index=False)

{'paths': ['s3://aje-analytics-ps-backup/Output/0_Final_PS/base_pedidos_final_2026-04-01.csv'],
 'partitions_values': {}}

In [42]:
# # Apaga el Kernel para luego poder usar los demás notebooks sin llenar la memoria
# import IPython
# app = IPython.get_ipython()
# app.kernel.do_shutdown(False)  # True indica apagar completamente el kernel